services:
  course-service-db:
    image: mysql:8.0
    container_name: course-service-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: lms_course_service
    ports:
      - "3308:3306"
    volumes:
      - course-service-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  course-service:
    build: ./backend/services/course-service
    container_name: course-service
    ports:
      - "7878:7878"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://course-service-db:3306/lms_course_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      course-service-db:
        condition: service_healthy

  admin-frontend:
    build: ./frontend/Admin
    container_name: admin-frontend
    ports:
      - "3001:3001"
    depends_on:
      - course-service

  user-service-db:
    image: mysql:8.0
    container_name: user-service-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: lms_user_service
    ports:
      - "3307:3306"
    volumes:
      - user-service-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./backend/services/user-service
    container_name: user-service
    ports:
      - "7879:7879"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-service-db:3306/lms_user_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      user-service-db:
        condition: service_healthy

  client-frontend:
    build: ./frontend/Client
    container_name: client-frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service

volumes:
  course-service-db-data:
  user-service-db-data:
