spring:
  application:
    name: LMS Course Service

  datasource:
    url: jdbc:mysql://localhost:3306/lms_course_service?createDatabaseIfNotExist=true
    username: root
    password: Rasan@23394
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 7878
